blank_issues_enabled: true
contact_links:
  - name: "Questions about OSMTracker"
    url: "https://github.com/labexp/osmtracker-android/discussions/categories/q-a"
    about: "Ask questions and discuss with the OSMTracker community in GitHub Discussions."
