name: Test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "develop"
      - "master"

jobs:
  build:
    runs-on: macos-latest # https://github.com/marketplace/actions/android-emulator-runner

    strategy:
      fail-fast: false
      matrix:
        api-level: [16, 23, 29]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Gradle validation
        uses: gradle/wrapper-validation-action@v1

      - name: Java setup
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: default
          arch: x86
          profile: Nexus 6
          script: ./gradlew connectedAndroidTest test
